[tool.black]
line-length = 90 # override black's default line-length
force-exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.isort]
# make it compatible with black
profile = "black"
atomic = true
combine_as_imports = true
line_length = 90

[tool.pyright]
include = ["src"]
ignore = [
    "**/__pycache__",
    "**/notes",
    ".git",
    "**/bin/**",
    "**/site-packages/**",
    "**/.pytest_cache/**"
    ]

[tools.pylint.MASTER]
init-hook='import sys; sys.path.append("$HOME/miniconda3/envs/IFT870/lib/python3.10/site-packages/")'
[tool.pylint.main]
extension-pkg-allow-list = [
    "numpy"
]
ignore-pattern = ["bin/*"]

[tool.pylint.messages_control]
disable = [
    "bad-inline-option",
    "file-ignored",
    "import-error",
    "invalid-name",
    "line-too-long",
    "locally-disabled",
    "missing-module-docstring",
    "raw-checker-failed",
    "redefined-outer-name",
    "suppressed-message"
]

[tool.pylint.typecheck]
generated-members = ["numpy.*"]

[tool.pylint.format]
max-line-length = 120
