# shellcheck shell=bash

# Ignore non-interactive shells
[[ $- == *i* ]] || return

# Generic aliases, not env specific. Called in ~/.bashrc
alias htopme="htop -u ${USER}"

# History Aliases
alias h="history 30"                          # last few history commands
alias ht="HISTTIMEFORMAT='%F_%T  ' history 30" # history with time stamps

# ls aliases
alias llt="ls -ahlFtr" #reverse time lookup (oldest last), w size prefixes
alias lla='ls -ahlF'
alias ll='ls -hlF'
alias la='ls -A'
alias l='ls -CF'

# Common commands
alias cp="cp -vi --preserve=timestamps"
alias mv="mv -v --no-clobber"
alias pwdp="pwd -P"
alias open="xdg-open"

# xclip clipboard management
# alias pbcopy="xclip -sel clip"
# function copy() {
#   echo -n "$1" | xclip -selection clipboard
# }

# git
alias gs="git status"
alias gd="git diff"
alias gds="git diff --staged"
alias git-update="git fetch && git status"
alias gcno="git commit --no-verify"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Misc
# check if a process is stopping 'idle' status
alias check-idle="dbus-send --print-reply --dest=org.gnome.SessionManager /org/gnome/SessionManager org.gnome.SessionManager.GetInhibitors"

# pytest with auto cpu core usage (pytest-xdist required)
alias pytest="pytest -n auto"

# ctrl+ backtick will now expand aliases
if [ -t 1 ]
then
    # standard output is a tty
    # do interactive initialization
    bind '"\C-`": alias-expand-line'
fi
