# Generic aliases, not env specific. Called in ~/.bashrc

# History Aliases
alias h="history 30"                          # last few history commands
alias ht="HISTTIMEFORMAT='%F_%T  ' history 30" # history with time stamps

# ls aliases
alias llt="ls -ahlFtr" #reverse time lookup (oldest last), w size prefixes
alias lla='ls -ahlF'
alias ll='ls -hlF'
alias la='ls -A'
alias l='ls -CF'

# Misc
alias cp="cp -v --no-clobber"
alias mv="mv -v --no-clobber"
alias pwdp="pwd -P"

alias open="xdg-open"

# git
alias gs="git status"
alias gd="git diff"
alias gds="git diff --staged"
alias git-update="git fetch && git status"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
